/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#8ef2ff",
        "on-secondary-fixed": "#001f23",
        "on-error-container": "#93000a",
        "inverse-primary": "#a3c9ff",
        "on-tertiary-fixed": "#002112",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#d3e3ff",
        "on-secondary-container": "#006b75",
        "tertiary-fixed": "#6bfcb6",
        "background": "#f7f9fc",
        "tertiary-container": "#007d51",
        "on-primary-fixed-variant": "#004883",
        "on-surface": "#191c1e",
        "surface-tint": "#0060ab",
        "outline-variant": "#c1c7d3",
        "surface-container-high": "#e6e8eb",
        "secondary-container": "#79eefd",
        "tertiary-fixed-dim": "#49df9b",
        "tertiary": "#00623e",
        "outline": "#717783",
        "secondary-fixed-dim": "#60d7e5",
        "primary-container": "#1a6fbf",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#bcffd6",
        "primary-fixed-dim": "#a3c9ff",
        "on-primary-container": "#eaf1ff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e6",
        "primary": "#00569b",
        "surface-variant": "#e0e3e6",
        "on-primary-fixed": "#001c39",
        "surface-bright": "#f7f9fc",
        "inverse-on-surface": "#eff1f4",
        "on-tertiary-fixed-variant": "#005233",
        "surface-container": "#eceef1",
        "on-surface-variant": "#414751",
        "surface-dim": "#d8dadd",
        "surface": "#f7f9fc",
        "on-secondary": "#ffffff",
        "secondary": "#006972",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004f56"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max-width": "1440px",
        "margin-desktop": "40px",
        "base": "4px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "transcript-text": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "card-title": ["Inter", "sans-serif"],
        "data-label": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "transcript-text": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "card-title": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "data-label": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
